//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.10 at 12:32:28 PM BRT 
//


package ivan.slavka.jaxb.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ivan.slavka.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Pow_QNAME = new QName("", "pow");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Cost_QNAME = new QName("", "cost");
    private final static QName _Tgh_QNAME = new QName("", "tgh");
    private final static QName _Hand_QNAME = new QName("", "hand");
    private final static QName _Life_QNAME = new QName("", "life");
    private final static QName _Rule_QNAME = new QName("", "rule");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Multi_QNAME = new QName("", "multi");
    private final static QName _Card_QNAME = new QName("", "card");
    private final static QName _Loyalty_QNAME = new QName("", "loyalty");
    private final static QName _Typelist_QNAME = new QName("", "typelist");
    private final static QName _Rulelist_QNAME = new QName("", "rulelist");
    private final static QName _Deck_QNAME = new QName("", "deck");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ivan.slavka.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Deck }
     * 
     */
    public Deck createDeck() {
        return new Deck();
    }

    /**
     * Create an instance of {@link Card }
     * 
     */
    public Card createCard() {
        return new Card();
    }

    /**
     * Create an instance of {@link Typelist }
     * 
     */
    public Typelist createTypelist() {
        return new Typelist();
    }

    /**
     * Create an instance of {@link Multi }
     * 
     */
    public Multi createMulti() {
        return new Multi();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link Rulelist }
     * 
     */
    public Rulelist createRulelist() {
        return new Rulelist();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pow")
    public JAXBElement<String> createPow(String value) {
        return new JAXBElement<String>(_Pow_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cost")
    public JAXBElement<String> createCost(String value) {
        return new JAXBElement<String>(_Cost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tgh")
    public JAXBElement<String> createTgh(String value) {
        return new JAXBElement<String>(_Tgh_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hand")
    public JAXBElement<String> createHand(String value) {
        return new JAXBElement<String>(_Hand_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "life")
    public JAXBElement<String> createLife(String value) {
        return new JAXBElement<String>(_Life_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rule")
    public JAXBElement<Object> createRule(Object value) {
        return new JAXBElement<Object>(_Rule_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Multi }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "multi")
    public JAXBElement<Multi> createMulti(Multi value) {
        return new JAXBElement<Multi>(_Multi_QNAME, Multi.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Card }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "card")
    public JAXBElement<Card> createCard(Card value) {
        return new JAXBElement<Card>(_Card_QNAME, Card.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "loyalty")
    public JAXBElement<String> createLoyalty(String value) {
        return new JAXBElement<String>(_Loyalty_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Typelist }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "typelist")
    public JAXBElement<Typelist> createTypelist(Typelist value) {
        return new JAXBElement<Typelist>(_Typelist_QNAME, Typelist.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rulelist }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rulelist")
    public JAXBElement<Rulelist> createRulelist(Rulelist value) {
        return new JAXBElement<Rulelist>(_Rulelist_QNAME, Rulelist.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Deck }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deck")
    public JAXBElement<Deck> createDeck(Deck value) {
        return new JAXBElement<Deck>(_Deck_QNAME, Deck.class, null, value);
    }

}
